name: Create release

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  create:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./package-lock.json
          node-version: 20.x

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Build project
        run: npm run build

      - name: Create release
        run: node ./scripts/create_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
