name: Create release

on: workflow_call

permissions:
  contents: write

jobs:
  create:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ./package-lock.json
          node-version: 20.x

      - name: Create new version file
        run: node ./scripts/create_version_file.js

      - name: Commit version file
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated version file
          default_author: github_actions

      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Build project
        run: npm run build

      - name: Create release
        run: node ./scripts/create_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
