name: Preflight

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  create-release:
    if: github.ref_name == 'main' && github.triggering_actor != 'github-actions[bot]'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/create_release.yaml
    secrets: inherit
