name: Create release Windows

on:
  push:
    branches:
      - spike-actions

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.8.0

      # Setup NASM (required for V8 assembly)
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1

      # Install LLVM/Clang (needed for Node.js >= 24)
      - name: Setup LLVM/Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: '15.0.7' # stable Clang works with Node.js 24
          directory: C:\llvm

      # Cache Node modules
      - name: Cache Node modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      # Install Node dependencies if cache missed
      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

      # Install Nexe globally
      - name: Install Nexe globally
        run: npm install -g nexe

      # Install CMake (Node.js build system requires it now)
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.0'

      # Run deploy.sh with Clang initialized
      - name: Run deploy.sh with Clang
        shell: bash
        run: |
          echo "Using Clang:"
          clang-cl --version
          bash ./deploy.sh
