name: Create release Windows

on:
  push:
    branches:
      - spike-actions

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Install NASM
        run: choco install nasm -y
