name: Create release Windows

on:
  push:
    branches:
      - spike-actions

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    # timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/setup-nasm@v1

      - name: Check NASM version
        run: nasm -v
