name: Create release Windows

on: workflow_call

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    timeout-minutes: 30
  steps:
    - name: Test Windows command
      run: |
        echo "✅ Windows runner is working"
        dir
