name: Create release Windows

on:
  push:
    branches:
      - spike-actions

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    # timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install NASM
        run: choco install nasm -y

      - name: Add NASM to PATH
        run: |
          echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\lib\nasm\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Check NASM version
        run: nasm -v
