name: Create release Windows

on:
  push:
    branches:
      - spike-actions

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    # timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1
      # Run deploy.sh with MSVC initialized
      - name: Run deploy.sh with MSVC
        shell: cmd
        run: 'nasm --version'
        # |
        #FOR /F "usebackq tokens=*" %%i IN (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) DO SET VS_PATH=%%i
        #call "%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat" x64
        #bash ./deploy.sh
