name: Create release Windows

on:
  push:
    branches:
      - spike-actions

permissions:
  contents: write

jobs:
  create:
    runs-on: windows-latest
    # timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Cache NASM
      - name: Cache NASM
        id: cache-nasm
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib\nasm
          key: nasm-${{ runner.os }}-v3

      # Install NASM if not cached
      - name: Install NASM
        if: steps.cache-nasm.outputs.cache-hit != 'true'
        run: choco install nasm -y
      - name: Add NASM to PATH
        run: echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Check NASM version
        run: nasm -v
